### ISSUE TITLE
Bug: Multiple DualSense controllers not correctly displaying info

### ISSUE THREAD

**Issue by TroyHickling** [alphamercury/ControllerTools#15]
This plugin is almost exactly what I've been needing, been having so much pain figuring out how much battery all my controllers have so thank you.
Just having an issue where it's only reporting the information for a single controller.

I have 4 DualSense controllers and the plugin correctly shows a row for each connected controller, however it only reports the status of the first controller.

IE if I have 4 controllers, 1 is 5% and the other 3 are 100%, if the 5% controller is connected first all controllers will show as 5%. Whereas if any of the 100% controllers connect first all of them would show as 100%
This is the same for the charging indicator as well.

**Comment by ludokx** [comment]
@TroyHickling can you please try installing this build? That should fix the issue. Ping us ideally on [Discord](https://discord.com/channels/960281551428522045/1061857365659496478) or here if you need help installing.

[controller-tools-1.0.0-rc.1.zip](https://github.com/alphamercury/ControllerTools/files/10473321/controller-tools-1.0.0-rc.1.zip)

**Comment by TroyHickling** [comment]
@ludokx just given it a go and looks to be all great. Plugged each controller in 1 by 1 and they correctly showed which is charging and each controller had a diff charge percentage as expected. 

Thanks for the quick turnaround!
