### ISSUE TITLE
Feature request: Support Stadia Controller

### ISSUE THREAD

**Issue by vordenken** [alphamercury/ControllerTools#21]
This looks awesome! Would it be possible to add google stadia controller support to the plugin?

**Comment by ludokx** [comment]
Hi @vordenken, we added support for Stadia with version 0.4.0 which is released in the store. Did you try that version? Is it not working for you?

**Comment by jfernandez** [comment]
We should probably update the list of supported controllers in the README

**Comment by vordenken** [comment]
> Hi @vordenken, we added support for Stadia with version 0.4.0 which is released in the store. Did you try that version? Is it not working for you?

You're right sorry, I had an older version installed and didn't see anything in the README or the install popup on my steam deck about stadia so I thought its not supported.
I installed 0.40 and it works like a charm :) Thanks for this awesome plugin!

**Comment by ludokx** [comment]
Awesome, glad to hear it's working and thanks for the kind words :)
